require 'purchase_processor/configuration'
require 'purchase_processor/adapter/adapter'
require 'purchase_processor/adapter/free/free_adapter'
require 'purchase_processor/adapter/paypal/paypal_adapter'
require 'purchase_processor/adapter/stripe/stripe_adapter'
